version: "0.2"

services:
    postgresql:
        image: postgres:14.4-alpine
        container_name: webshopdb
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=webshopadmin
            - POSTGRES_PASSWORD=remekpass
            - POSTGRES_DB=remekwebshopdb
    vremek:
        build: .
        ports:
            - "8080:8080"
        depends_on:
            - postgresql
        environment:
            - WEBSHOP_URL=jdbc:postgresql://localhost:5432/remekwebshopdb
            - WEBSHOP_USER=webshopadmin
            - WEBSHOP_PASSWORD=remekpass
